#include "fft/fft.h"
#include <stdio.h>
#include <stdbool.h>
#include <math.h>

#define EPSILON 0.1f
#define TEST_SIZE 1024
#define PI 3.14159265358979323846f
#define SAMPLE_RATE 44100

//This is the O(n^2) implementation, which I will use to check the values
// generated by my fft
static void slowDFT(float *samples, int n, float *expected) {
    for (int k = 0; k < n / 2; k++) {
        float real = 0.0f;
        float imaginary = 0.0f;

        for (int t = 0; t < n; t++) {
            float angle = 2.0f * PI * k * t / n;

            real += samples[t] * cosf(angle);
            imaginary -= samples[t] * sinf(angle);
        }

        expected[k] = sqrtf(real * real + imaginary * imaginary);
    }
}

static bool compareFloatLists(float *actual, float *expected, int len){
    for(int n = 0; n<len; n++){
        if(fabsf(actual[n]-expected[n])>EPSILON){
            return false;
        }
    }
    return true;
}

//This tests that if there is no signal, then all the bins should be 0
static bool testZero(void){
    float samples[TEST_SIZE];
    float bins[TEST_SIZE / 2];
    float expected[TEST_SIZE / 2];

    for (int i = 0; i < TEST_SIZE; i++) {
        samples[i] = 0.0f;
    }

    for (int i = 0; i < TEST_SIZE / 2; i++) {
        expected[i] = 0.0f;
    }
    fft(samples,TEST_SIZE,bins);
    return compareFloatLists(bins,expected,4);
}

//This tests an impulse. This test case occurs because the polynomial
// is just a constant so it should return 1 for all bins
static bool testImpulse(void) {
    float samples[TEST_SIZE];
    float bins[TEST_SIZE / 2];
    float expected[TEST_SIZE / 2];

    samples[0] = 1.0f;

    for (int i = 1; i < TEST_SIZE; i++) {
        samples[i] = 0.0f;
    }

    for (int i = 0; i < TEST_SIZE / 2; i++) {
        expected[i] = 1.0f;
    }

    fft(samples, TEST_SIZE, bins);

    return compareFloatLists(bins, expected, TEST_SIZE / 2);
}

//This tests DC, which has a frequency of 0
// This means that bin 1 should have an output of n
// and the rest should be 0
static bool testDC(void) {
    float samples[TEST_SIZE];
    float bins[TEST_SIZE / 2];
    float expected[TEST_SIZE / 2];

    for (int i = 0; i < TEST_SIZE; i++) {
        samples[i] = 1.0f;
    }

    expected[0] = (float)TEST_SIZE;
    for (int i = 1; i < TEST_SIZE / 2; i++) {
        expected[i] = 0.0f;
    }

    fft(samples, TEST_SIZE, bins);

    return compareFloatLists(bins, expected, TEST_SIZE / 2);
}

static bool testCosineBinOne(void) {
    float samples[TEST_SIZE];
    float bins[TEST_SIZE / 2];
    float expected[TEST_SIZE / 2];

    for (int i = 0; i < TEST_SIZE; i++) {
        samples[i] = cosf(2.0f * PI * 1.0f * i / TEST_SIZE);
    }

    expected[0] = 0.0f;
    expected[1] = TEST_SIZE / 2.0f;
    expected[2] = 0.0f;
    expected[3] = 0.0f;

    fft(samples, TEST_SIZE, bins);

    return compareFloatLists(bins, expected, TEST_SIZE / 2);
}

static bool testMixedSignalOne(void) {
    float samples[TEST_SIZE];
    float bins[TEST_SIZE / 2];
    float expected[TEST_SIZE / 2];

    for (int i = 0; i < TEST_SIZE; i++) {
        samples[i] =
            1.0f  * sinf(2.0f * PI * 440.0f  * i / SAMPLE_RATE) +  // A4
            0.8f  * sinf(2.0f * PI * 880.0f  * i / SAMPLE_RATE) +  // A5
            0.6f  * sinf(2.0f * PI * 1760.0f * i / SAMPLE_RATE) +  // A6
            0.4f  * sinf(2.0f * PI * 261.63f * i / SAMPLE_RATE) + // C4
            0.3f  * cosf(2.0f * PI * 523.25f * i / SAMPLE_RATE) + // C5
            0.25f * sinf(2.0f * PI * 1000.0f * i / SAMPLE_RATE) +
            0.15f * cosf(2.0f * PI * 3000.0f * i / SAMPLE_RATE);
    }

    slowDFT(samples, TEST_SIZE, expected);

    fft(samples, TEST_SIZE, bins);

    return compareFloatLists(bins, expected, TEST_SIZE / 2);
}

static bool testMixedSignalTwo(void) {
    float samples[TEST_SIZE];
    float bins[TEST_SIZE / 2];
    float expected[TEST_SIZE / 2];

    for (int i = 0; i < TEST_SIZE; i++) {
        samples[i] =
            1.2f  * sinf(2.0f * PI * 110.0f  * i / SAMPLE_RATE) +  // A2
            0.9f  * sinf(2.0f * PI * 220.0f  * i / SAMPLE_RATE) +  // A3
            0.7f  * cosf(2.0f * PI * 330.0f  * i / SAMPLE_RATE) +
            0.5f  * sinf(2.0f * PI * 660.0f  * i / SAMPLE_RATE) +
            0.25f * cosf(2.0f * PI * 1320.0f * i / SAMPLE_RATE);
    }

    slowDFT(samples, TEST_SIZE, expected);

    fft(samples, TEST_SIZE, bins);

    return compareFloatLists(bins, expected, TEST_SIZE / 2);
}

static bool testMixedSignalThree(void) {
    float samples[TEST_SIZE];
    float bins[TEST_SIZE / 2];
    float expected[TEST_SIZE / 2];

    for (int i = 0; i < TEST_SIZE; i++) {
        samples[i] =
            0.8f  * sinf(2.0f * PI * 55.0f    * i / SAMPLE_RATE) +  // A1
            0.6f  * cosf(2.0f * PI * 440.0f   * i / SAMPLE_RATE) +  // A4
            0.45f * sinf(2.0f * PI * 1000.0f  * i / SAMPLE_RATE) +
            0.35f * cosf(2.0f * PI * 2500.0f  * i / SAMPLE_RATE) +
            0.2f  * sinf(2.0f * PI * 6000.0f  * i / SAMPLE_RATE) +
            0.1f  * cosf(2.0f * PI * 10000.0f * i / SAMPLE_RATE);
    }

    slowDFT(samples, TEST_SIZE, expected);

    fft(samples, TEST_SIZE, bins);

    return compareFloatLists(bins, expected, TEST_SIZE / 2);
}

int main(void){
    if(!testZero()){
        printf("Test zero list failed\n");
    }else{
        printf("Test zero list passed\n");
    }

    if(!testImpulse()){
        printf("Test impulse failed\n");
    }else{
        printf("Test impulse passed\n");
    }

    if(!testDC()){
        printf("Test DC failed\n");
    }else{
        printf("Test DC passed\n");
    }

    if (!testCosineBinOne()) {
        printf("testCosineBinOne failed\n");
    } else {
        printf("testCosineBinOne passed\n");
    }

    if(!testMixedSignalOne()){
        printf("testMixedSignalOne failed\n");
    }else{
        printf("testMixedSignalOne passed\n");
    }

    if(!testMixedSignalTwo()){
        printf("testMixedSignalTwo failed\n");
    }else{
        printf("testMixedSignalTwo passed\n");
    }

    if(!testMixedSignalThree()){
        printf("testMixedSignalThree failed\n");
    }else{
        printf("testMixedSignalThree passed\n");
    }
}